### ISSUE TITLE
Unit test issues

### ISSUE THREAD

**Issue by miccheng** [juliatong/graph#1]
1. Dead code

  - Unused `grids` variable in tests
    - https://github.com/juliatong/graph/blob/4e3e9f33f1559f1a3458b1a147068bc6e400d053/graph/src/test/java/com/example/graph/client/GraphDrawTestSuite.java#L91
    - https://github.com/juliatong/graph/blob/4e3e9f33f1559f1a3458b1a147068bc6e400d053/graph/src/test/java/com/example/graph/client/GraphDrawTestSuite.java#L69
    - https://github.com/juliatong/graph/blob/4e3e9f33f1559f1a3458b1a147068bc6e400d053/graph/src/test/java/com/example/graph/client/GraphDrawTestSuite.java#L48

2. Simplify expectation setup

    - You could construct a string instead of the heavy setup:

    ```java
    String expected = "------\n" +
                "|    |\n" +
                "|    |\n" +
                "|  xx|\n" +
                "------\n";
    assertEquals(expected, actual);
    ```
  
   Instead of: https://github.com/juliatong/graph/blob/4e3e9f33f1559f1a3458b1a147068bc6e400d053/graph/src/test/java/com/example/graph/client/GraphDrawTestSuite.java#L99-L100

3. Test suites that runs [multiple tests](https://github.com/juliatong/graph/blob/master/graph/src/test/java/com/example/graph/client/GraphDrawTestSuite.java), you need to reset the canvas.
  https://github.com/juliatong/graph/blob/4e3e9f33f1559f1a3458b1a147068bc6e400d053/graph/src/test/java/com/example/graph/client/GraphDrawTestSuite.java#L36

**Comment by juliatong** [comment]
updated
